[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "A cheat mod for developers. Powered by TestingLib."
websiteUrl = "https://github.com/Hamunii/DevTools"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-TestingLib = "1.1.0"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/DevTools.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "tools", ]